name = "llnd-assessment-portal"
compatibility_date = "2026-01-24"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "llnd-core-db"
database_id = "e4cccf89-6734-48b3-8d0d-0ab38c792958"
migrations_dir = "migrations"

# KV namespace for Astro sessions
[[kv_namespaces]]
binding = "SESSION"
id = "f74f4299c4ab4857ac43f36b12d30e95"

# Observability
[observability]
enabled = true
